<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Label="Nuget">
    <PackageId>tryAGI.GitHub</PackageId>
    <Description>Generated C# SDK based on the official GitHub REST OpenAPI specification.</Description>
    <PackageTags>api;client;sdk;dotnet;openapi;generated;github;rest;tryagi</PackageTags>
    <RepositoryUrl>https://github.com/HavenDV/GitHub.NET</RepositoryUrl>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="PolySharp" Version="1.16.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
