name: Build, test and publish
on:
  push:
    branches:
      - main

jobs:
  build-test-publish:
    name: Build, test and publish
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      generate-build-number: false
      conventional-commits-publish-conditions: false
      enable-caching: false
      project-path: src/libs/GitHub/GitHub.csproj
      run-tests: false
      additional-command: 'dotnet test src/tests/GitHub.IntegrationTests/GitHub.IntegrationTests.csproj --configuration Release --logger GitHubActions'
    secrets:
      nuget-key: ${{ secrets.NUGET_KEY }}
